#ifndef DYNAMIC_GRAPH_REPRESENTATION_LEARNING_WITH_METROPOLIS_HASTINGS_CONFIG_H
#define DYNAMIC_GRAPH_REPRESENTATION_LEARNING_WITH_METROPOLIS_HASTINGS_CONFIG_H

namespace dynamic_graph_representation_learning_with_metropolis_hastings {};
namespace dygrl = dynamic_graph_representation_learning_with_metropolis_hastings;

#include <globals.h>
#include <types.h>

#endif // DYNAMIC_GRAPH_REPRESENTATION_LEARNING_WITH_METROPOLIS_HASTINGS_CONFIG_H
