#ifndef GLOBALS_H
#define GLOBALS_H

namespace config
{
    // determines the number of walks per vertex to be generated by the walkers
    uint8_t walks_per_vertex   = 1;

    // determines the length of one random walk
    uint8_t walk_length        = 5;

    // determines the type of random walk model to use
    auto random_walk_model     = types::RandomWalkModelType::DEEPWALK;

    // determines parameter P for node2vec model
    float paramP               = 4;

    // determines parameter Q for node2vec model
    float paramQ               = 1;

    // determines the initialization strategy for metropolis hastings samplers
    auto sampler_init_strategy = types::SamplerInitStartegy::WEIGHT;

    // random number generator
    auto random                = utility::Random(std::time(nullptr));

    // use range search when searching in walk-trees
    auto range_search_mode     = true;

    // determines whether to produce and update the walks in a deterministic way
    auto deterministic_mode    = true;

	// serial or parallel
	auto parallel_merge_wu     = true;

	// merge every x batches
	int merge_frequency = 1;
}

#endif
