#ifndef DYNAMIC_GRAPH_REPRESENTATION_LEARNING_WITH_METROPOLIS_HASTINGS_GLOBALS_H
#define DYNAMIC_GRAPH_REPRESENTATION_LEARNING_WITH_METROPOLIS_HASTINGS_GLOBALS_H

namespace config
{
    // determines the number of walks per vertex to be generated by the walkers
    constexpr uint8_t walks_per_vertex  = 1;

    // determines the length of one random walk
    constexpr uint8_t walk_length       = 5;

    // determines the type of random walk model to use
    constexpr auto random_walk_model    = types::RandomWalkModelType::DEEPWALK;

    // determines parameter P for node2vec model
    constexpr float paramP               = 0.5;

    // determines parameter Q for node2vec model
    constexpr float paramQ               = 0.2;

    // determines the initialization strategy for metropolis hastings samplers
    constexpr auto sampler_init_strategy = types::SamplerInitStartegy::BURNIN;

    // random number generator
    auto random                          = utility::Random(0);
}

#endif // DYNAMIC_GRAPH_REPRESENTATION_LEARNING_WITH_METROPOLIS_HASTINGS_GLOBALS_H
